<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon; // 日付生成用
use Illuminate\Support\Facades\Hash;

class MasterDataSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('PRAGMA foreign_keys = OFF;');
        $now = Carbon::now();

        // 1. 既存データをクリア
        DB::table('facility_slots')->truncate(); 
        DB::table('facility_purpose_equipments')->truncate();
        DB::table('facility_purposes')->truncate();
        DB::table('facilities')->truncate();
        DB::table('slots')->truncate();
        DB::table('purposes')->truncate();
        DB::table('equipments')->truncate();
        DB::table('buildings')->truncate();

        // 2. 建物のサンプルデータ
        DB::table('buildings')->insert([
            ['name' => '神明いきいきプラザ', 'address' => '港区神明', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '虎ノ門いきいきプラザ', 'address' => '港区虎ノ門', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '三田いきいきプラザ', 'address' => '港区三田', 'created_at' => $now, 'updated_at' => $now],
            ['name' => '赤坂ヘルシーナ', 'address' => '港区赤坂', 'created_at' => $now, 'updated_at' => $now],
        ]);

        // 3. 施設のサンプルデータ
        DB::table('facilities')->insert([
            ['building_id' => 1, 'name' => '会議室A', 'created_at' => $now, 'updated_at' => $now],
            ['building_id' => 1, 'name' => '会議室B', 'created_at' => $now, 'updated_at' => $now],
            ['building_id' => 1, 'name' => '会議室C', 'created_at' => $now, 'updated_at' => $now],
            ['building_id' => 1, 'name' => '会議室D', 'created_at' => $now, 'updated_at' => $now],
            ['building_id' => 1, 'name' => '料理室', 'created_at' => $now, 'updated_at' => $now],
            ['building_id' => 1, 'name' => '体育館', 'created_at' => $now, 'updated_at' => $now],
            ['building_id' => 1, 'name' => 'ダンススタジオ', 'created_at' => $now, 'updated_at' => $now],
            ['building_id' => 1, 'name' => '音楽スタジオ', 'created_at' => $now, 'updated_at' => $now],
            ['building_id' => 2, 'name' => '会議室A', 'created_at' => $now, 'updated_at' => $now],
            ['building_id' => 3, 'name' => '会議室A', 'created_at' => $now, 'updated_at' => $now],
            ['building_id' => 3, 'name' => '会議室B', 'created_at' => $now, 'updated_at' => $now],
            ['building_id' => 3, 'name' => '料理室', 'created_at' => $now, 'updated_at' => $now],
            ['building_id' => 1, 'name' => '会議室AB', 'created_at' => $now, 'updated_at' => $now],
        ]);
            

        // 4. 時間帯スロット
        DB::table('slots')->insert([
            ['slot_id' => 1, 'name' => '午前', 'created_at' => $now, 'updated_at' => $now],
            ['slot_id' => 2, 'name' => '午後', 'created_at' => $now, 'updated_at' => $now],
            ['slot_id' => 3, 'name' => '夜間', 'created_at' => $now, 'updated_at' => $now],
            ['slot_id' => 4, 'name' => '終日', 'created_at' => $now, 'updated_at' => $now],
        ]);

        // 5. 利用目的
        DB::table('purposes')->insert([
        
            ["name" => "会議", "created_at" => $now, "updated_at" => $now],
            ["name" => "茶道", "created_at" => $now, "updated_at" => $now],
            ["name" => "書道", "created_at" => $now, "updated_at" => $now],
            ["name" => "演劇", "created_at" => $now, "updated_at" => $now],
            ["name" => "料理", "created_at" => $now, "updated_at" => $now],
            ["name" => "ダンス", "created_at" => $now, "updated_at" => $now],
            ["name" => "音楽", "created_at" => $now, "updated_at" => $now],
            ["name" => "カラオケ", "created_at" => $now, "updated_at" => $now],
            ["name" => "バスケットボール", "created_at" => $now, "updated_at" => $now],
            ["name" => "バレーボール", "created_at" => $now, "updated_at" => $now],
            ["name" => "卓球", "created_at" => $now, "updated_at" => $now],
        ]);

        // 6. 付帯設備
        DB::table('equipments')->insert([
            ["name" => "マイク・スピーカー", "created_at" => $now, "updated_at" => $now],
            ["name" => "バスケットボール", "created_at" => $now, "updated_at" => $now],
            ["name" => "プロジェクター", "created_at" => $now, "updated_at" => $now],
            ["name" => "ホワイトボード", "created_at" => $now, "updated_at" => $now],
            ["name" => "ビブス", "created_at" => $now, "updated_at" => $now],
            ["name" => "バレーボール支柱・ネット", "created_at" => $now, "updated_at" => $now],
            ["name" => "卓球台・ネット", "created_at" => $now, "updated_at" => $now],
            ["name" => "カラオケ機材", "created_at" => $now, "updated_at" => $now],
            ["name" => "書道セット", "created_at" => $now, "updated_at" => $now],
            ["name" => "料理セット", "created_at" => $now, "updated_at" => $now],
            ["name" => "得点板", "created_at" => $now, "updated_at" => $now],
        ]);

        // 7. 紐付けデータ（中間テーブルもタイムスタンプが必要な場合は追加）
        DB::table('facility_purposes')->insert([
            ["facility_id" => 1, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 7, "purpose_id" => 2, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 10, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 7, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 7, "purpose_id" => 10, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 7, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 7, "purpose_id" => 7, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 1, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 17, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 17, "purpose_id" => 10, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 17, "purpose_id" => 2, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 17, "purpose_id" => 7, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 17, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 2, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 2, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 3, "purpose_id" => 7, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 3, "purpose_id" => 10, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 3, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 3, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 4, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 4, "purpose_id" => 6, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 4, "purpose_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 8, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 2, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 5, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 5, "purpose_id" => 12, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 2, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 3, "purpose_id" => 7, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 3, "purpose_id" => 10, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 3, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 3, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 4, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 4, "purpose_id" => 6, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 4, "purpose_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 8, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 2, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 5, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 5, "purpose_id" => 12, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 10, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 7, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 6, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 2, "created_at" => $now,  "updated_at" => $now],
            ["facility_id" => 4, "purpose_id" => 6, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 4, "purpose_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 8, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 2, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 5, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 5, "purpose_id" => 12, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 10, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 7, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 6, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 2, "created_at" => $now,  "updated_at" => $now],
            ["facility_id" => 6, "purpose_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 5, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 5, "purpose_id" => 12, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 10, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 7, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 6, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 2, "created_at" => $now,  "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 8, "purpose_id" => 7, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 6, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 9, "purpose_id" => 2, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 10, "purpose_id" => 6, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 10, "purpose_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 10, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 11, "purpose_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 11, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 11, "purpose_id" => 6, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 11, "purpose_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 12, "purpose_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_id" => 12, "purpose_id" => 12, "created_at" => $now, "updated_at" => $now],

        ]);

        DB::table('facility_purpose_equipments')->insert([
            ["facility_purpose_id" => 3, "equipment_id" => 2, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 2, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 2, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 2, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 8, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 8, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 8, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 9, "equipment_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 9, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 9, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 9, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 10, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 10, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 10, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 11, "equipment_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 11, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 11, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 11, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 1, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 1, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 1, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 13, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 13, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 13, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 16, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 16, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 16, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 19, "equipment_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 19, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 19, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 19, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 20, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 20, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 20, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 15, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 16, "equipment_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 21, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 21, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 21, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 22, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 22, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 22, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 23, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 23, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 23, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 24, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 24, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 24, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 26, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 26, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 26, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 27, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 27, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 27, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 27, "equipment_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 28, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 28, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 28, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 29, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 29, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 29, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 30, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 30, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 30, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 31, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 31, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 31, "equipment_id" => 10, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 31, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 32, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 34, "equipment_id" => 7, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 36, "equipment_id" => 6, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 36, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 36, "equipment_id" => 8, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 34, "equipment_id" => 6, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 3, "equipment_id" => 12, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 39, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 39, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 40, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 40, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 40, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 40, "equipment_id" => 9, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 41, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 41, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 41, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 42, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 42, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 42, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 4, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 4, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 4, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 43, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 43, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 43, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 43, "equipment_id" => 8, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 44, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 44, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 44, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 45, "equipment_id" => 10, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 45, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 45, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 45, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 46, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 46, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 46, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 6, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 6, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 6, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 47, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 47, "equipment_id" => 10, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 47, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 47, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 48, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 48, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 48, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 49, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 49, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 49, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 53, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 53, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 53, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 54, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 54, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 54, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 55, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 55, "equipment_id" => 10, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 55, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 55, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 56, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 56, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 56, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 57, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 57, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 57, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 58, "equipment_id" => 1, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 58, "equipment_id" => 3, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 58, "equipment_id" => 11, "created_at" => $now, "updated_at" => $now],
            ["facility_purpose_id" => 58, "equipment_id" => 4, "created_at" => $now, "updated_at" => $now],
        ]);

        DB::table('facility_slots')->insert([ 
            [ "facility_id" => 6, "slot_id" => 3, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 1, "slot_id" => 1, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 1, "slot_id" => 2, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 1, "slot_id" => 3, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 10, "slot_id" => 1, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 10, "slot_id" => 2, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 10, "slot_id" => 3, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 17, "slot_id" => 4, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 17, "slot_id" => 1, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 17, "slot_id" => 3, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 17, "slot_id" => 2, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 1, "slot_id" => 4, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 7, "slot_id" => 3, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 7, "slot_id" => 2, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 7, "slot_id" => 4, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 7, "slot_id" => 1, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 2, "slot_id" => 3, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 2, "slot_id" => 2, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 2, "slot_id" => 1, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 2, "slot_id" => 4, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 3, "slot_id" => 2, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 3, "slot_id" => 4, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 3, "slot_id" => 1, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 3, "slot_id" => 3, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 4, "slot_id" => 3, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 4, "slot_id" => 4, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 4, "slot_id" => 1, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 4, "slot_id" => 2, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 5, "slot_id" => 2, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 5, "slot_id" => 1, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 5, "slot_id" => 4, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 5, "slot_id" => 3, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 8, "slot_id" => 4, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 8, "slot_id" => 3, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 8, "slot_id" => 1, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 8, "slot_id" => 2, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 9, "slot_id" => 3, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 10, "slot_id" => 4, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 11, "slot_id" => 1, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 11, "slot_id" => 4, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 11, "slot_id" => 2, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 11, "slot_id" => 3, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 12, "slot_id" => 3, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 12, "slot_id" => 4, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 12, "slot_id" => 2, "created_at" => $now, "updated_at" => $now],
            [ "facility_id" => 12, "slot_id" => 1, "created_at" => $now, "updated_at" => $now],

        ]);
        DB::table('users')->insert([ 
            [
            'name' => 'Administrator',
            'email' => 'admin@event-plus.test',
            'password' => Hash::make('password'), // 本番環境では別の方法で
            'telephone' => '03-1234-5678',
            'address' => '東京都千代田区',
            'company' => 'Event Plus',
            'role' => 'administrator',
            'created_at' => $now,
            'updated_at' => $now,
            ],
        ]);

        DB::statement('PRAGMA foreign_keys = ON;');
    }
}